modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/samolego/MobDisguises/issues"
license = "UNLICENSE"

[[mods]]
modId = "mobdisguises"
version = "${version}"
displayName = "Mob Disguises"
authors = "samo_lego"
description = '''
Showcasing abilities of DisguiseLib.
'''
#logoFile = ""

[[dependencies.mobdisguises]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.mobdisguises]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.mobdisguises]]
modId = "disguiselib"
mandatory = true
versionRange = "[1.0.1,)"
ordering = "AFTER"
side = "SERVER"